### PR TITLE
Update to ReadStat 1.1.9

### LINKED ISSUE #529: Issue with some labels not applied when reading SAS
I'm reading a SAS database into R using our format file. I see the labels are applied to only some of the columns. In SAS, I see the format is applied to each column, just fine, so I'm not sure why the catalog file is not working when reading into R.

I put a sample of the database and format file [here](https://github.com/jacciz/haven_label)

Here's an example of two columns; one labels are not applied, one labels are applied.
``` r
test <- read_sas("person18.sas7bdat", "format17.sas7bcat")

attributes(test$ROLE) # labels are not applied
#> $format.sas
#> [1] "F17ROLE"
attributes(test$SFTYEQP) # labels are applied
#> $format.sas
#> [1] "F17SFTYEQP"
#> 
#> $class
#> [1] "haven_labelled"
#> 
#> $labels
#>                     Shoulder & Lap Belt                           Lap Belt Only 
#>                                     101                                     102 
#>                      Shoulder Belt Only                   Restraint Use Unknown 
#>                                     103                                     104 
#>            None Used - Vehicle Occupant           Restraint Used - Type Unknown 
#>                                     105                                     106 
#> Child Restraint System - Forward Facing    Child Restraint System - Rear Facing 
#>                                     107                                     108 
#>                            Booster Seat          Child Restraint - Type Unknown 
#>                                     109                                     110 
#>                          Not Applicable                                   Other 
#>                                     990                                     998
```

### LINKED ISSUE #653: read_sas with catalog_file resulted in failed to parse error
I'm new to R and Haven. I'm working with data from [NHTSA](https://www.nhtsa.gov/file-downloads?p=nhtsa/downloads/CISS/2019/). NHTSA provides SAS data files and both 32-bit and 64-bit catalog files.  

I am trying to use Haven to import SAS files. The read_sas function works well if no catalog file is specified. If I specify a catalog file, I get an error: "Error: Failed to parse xxx/formats_32.sas7bcat: Unable to allocate memory." This occurs using both the 32-bit and 64-bit catalog files.

I tried to put together a reprex but get an error when running the reprex: "Error: pandoc document conversion failed with error 1". I haven't solved that one, so I will paste the code I'm using to see if any can assist as is.

I'm using:
 - RStudio 2021.09.1 Build 372
 - R 4.1.2
 - Haven 2.4.3

In the code below, I renamed the sas7bcat files from the supplied files to keep track of whether it is 32 or 64 bit.

```r
library(haven)
gv <- read_sas("gv.sas7bdat")
## This successfully produces a data frame.
gv_32 <- read_sas(data_file = "gv.sas7bdat", catalog_file = "formats_32.sas7bcat")
##This results in error "Error: Failed to parse C:/.../formats.sas7bcat: Unable to allocate memory."

gv
# A tibble: 4,982 x 105
   CASEID   PSU CASENO CASENUMBER   CATEGORY VEHNO VIN    VINLENGTH  MAKE MODEL MODELYR BODYTYPE BODYCAT
    <dbl> <dbl>  <dbl> <chr>           <dbl> <dbl> <chr>      <dbl> <dbl> <dbl>   <dbl>    <dbl>   <dbl>
 1  12475    10      1 1-10-2019-0~       10     1 2G1WF~        17    20     2    2002        4       1
 2  12475    10      1 1-10-2019-0~       10     2 1G2WP~        17    22    20    1999        2       1
 3  12579    10      2 1-10-2019-0~        9     1 1GNDU~        17    20   443    2003       20       4
 4  12579    10      2 1-10-2019-0~        9     2 KMHDN~        17    55    35    2002        4       1
 5  12725    10      3 1-10-2019-0~        6     1 1G6KS~        17    19    14    2004        4       1
 6  12725    10      3 1-10-2019-0~        6     2 3FADP~        17    12    32    2014        4       1
 7  12726    10      4 1-10-2019-0~        7     1 4T1BF~        17    49    40    2013        4       1
 8  12805    10      5 1-10-2019-0~        4     1 1G1PE~        17    20    25    2016        4       1
 9  12898    10      6 1-10-2019-0~        4     1 5TDJK~        17    49   403    2016       14       3
10  12898    10      6 1-10-2019-0~        4     2 1FTYR~        17    12   471    2008       34       5
# ... with 4,972 more rows, and 92 more variables: VEHCLASS <dbl>, SPECUSE <dbl>, TRANSTAT <dbl>,
#   DAMPLANE <chr>, DAMSEV <dbl>, CURBWT <dbl>, CURBSRC <dbl>, CARGOWT <dbl>, CARGOSRC <dbl>,
#   INSPTYPE <dbl>, INSPLAG <dbl>, TOWED <dbl>, SPEEDLIMIT <dbl>, DRPRESENT <dbl>, PARALCOHOL <dbl>,
#   ALCTEST <dbl>, ALCTESTRESULT <dbl>, ALCTESTSRC <dbl>, PARDRUG <dbl>, DRUGTEST <dbl>, ZIP <chr>,
#   RACE <dbl>, ETHNICITY <dbl>, RELTOJUNCT <dbl>, TRAFFLOW <dbl>, RDLANES <dbl>, INITLANE <dbl>,
#   SURFTYPE <dbl>, SURFCOND <dbl>, ALIGNMENT <dbl>, PROFILE <dbl>, LINERIGHT <dbl>, LINELEFT <dbl>,
#   RUMBINIT <dbl>, RUMBROAD <dbl>, LIGHTCOND <dbl>, WEATHER <dbl>, TRAFDEV <dbl>, TRAFFUNCT <dbl>, ...
```

### LINKED ISSUE #680: Error in read_sas using catalog file
Hi, I am getting the error message "Error: Failed to parse formats.sas7bcat: Invalid file, or file has unsupported features. " when importing SAS data with a catalog file. This is the same error as in the closed  issue #34. The data import without catalog file works. 

I am using the latest haven version (2.5.0) and tested it with the development version on github. 

```r
fpath <- "path/to/sas/data/file"
catalog  <- "formats.sas7bcat"
sas_data <- haven::read_sas(fpath, catalog_file = catalog)

Error: Failed to parse catlog.sas7bcat: Invalid file, or file has unsupported features. 
```

### LINKED ISSUE #683: Haven: The file's timestamp string is invalid
I try to read SPSS format:
```
dataframe <- as.data.frame(read_sav("C:/~FilePath/Dataset.sav"))
```
and get:
```
Error in df_parse_sav_file(spec, encoding, user_na, cols_skip, n_max, : Failed to parse ~FilePath/Dataset: The file's timestamp string is invalid.
```
This has been posted in a closed issue [(The file's timestamp string is invalid #488)](https://github.com/tidyverse/haven/issues/488) and in a Stackoverflow question [([Difficulty with haven package Reading SPSS data in R](https://stackoverflow.com/questions/60006760/difficulty-with-haven-package-reading-spss-data-in-r))](https://stackoverflow.com/questions/60006760/difficulty-with-haven-package-reading-spss-data-in-r), but I have not found any solution yet.

### LINKED ISSUE #696: `catalog_file` ignored in `read_sas()` when file created on Unix system
Having to work with SAS files created a unix system (SAS 9.4), we observed the following using `read_sas()` with a `catalog_file` (haven 2.5.1, R 4.2.1):

The catalog file (sas7bcat) seems to be ignored (no message, no error) if created on Unix, while `read_sas()` works as expected for catalog files created on windows, irrespective of the system that the corresponding data file was created on.

The attached [zip](https://github.com/tidyverse/haven/files/9585025/haven_reprex_github.zip) contains a reproducible example with recreations of haven's example sas data sets `hadley.sas7bdat` and `formats.sas7bcat` in different variations: both were recreated twice using either

  * Windows: WINDOWS_64 or
  * Unix: HP_UX_64, RS_6000_AIX_64, SOLARIS_64, HP_IA64

All data sets have `wlatin1` encoding.  

Both data files can be read with the Windows catalog file with formats being applied as expected, but no formats are available when using the Unix catalog file.

### LINKED ISSUE #697: haven::read_sas unable to allocate memory for 16MB SAS page sizes
`haven::read_sas` cannot read a SAS data file with page size 16 MiB (16777216 bytes). Some data files with sizes slightly under 16 MiB also fail to read.

I would expect the attached sas7bdat files (which I have zipped to keep filesize under 10MB) to be read in by `haven::read_sas` and give a 10,000 row tibble with one column `empty` consisting only of empty strings.

[20221123 - haven bug report.zip](https://github.com/tidyverse/haven/files/10072630/20221123.-.haven.bug.report.zip)

```r
haven::read_sas('test_16766976.sas7bdat') # Succeeds
# # A tibble: 10,000 x 1
# empty
# <chr>
#   1 ""   
# 2 ""   
# 3 ""   
# 4 ""   
# 5 ""   
# 6 ""   
# 7 ""   
# 8 ""   
# 9 ""   
# 10 ""   
# # ... with 9,990 more rows

haven::read_sas('test_16776192.sas7bdat') # Fails
# Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, catalog_encoding = catalog_encoding,  : 
#                              Failed to parse <snip>/test_16776192.sas7bdat: Unable to allocate memory.
                           
haven::read_sas('test_16777216.sas7bdat') # Fails
# Error in df_parse_sas_file(spec_data, spec_cat, encoding = encoding, catalog_encoding = catalog_encoding,  : 
#                              Failed to parse <snip>/test_16777216.sas7bdat: Unable to allocate memory.
```

I generated these files in SAS using
```sas
* libname out "appropriate/path/here";

data out.test_16777216 (bufsize=16777216 compress=no);
length empty $3000;
do i = 1 to 10000; output; end;
drop i;
run;
* PROC CONTENTS to verify page size;
proc contents data=out.test_16777216 varnum; run;

data out.test_16776192 (bufsize=16776192 compress=no);
length empty $3000;
do i = 1 to 10000; output; end;
drop i;
run;
proc contents data=out.test_16776192 varnum; run;

data out.test_16766976 (bufsize=16766976 compress=no);
length empty $3000;
do i = 1 to 10000; output; end;
drop i;
run;
proc contents data=out.test_16766976 varnum; run;

```

**Workaround:** Set the default page size in SAS to 8MB with `-BUFSIZE 8M` or on a case-by-case basis. The default page size for my operating environment is 16M.

### LINKED ISSUE #705: `haven::read_sas()` unable to allocate memory for <16MB SAS page sizes
The same problem as in #697 can also happen with <16MB catalogs if one of the formats is considered invalid.
It is a kind of a corner case but I guess it can provide some information.

For instance, I have to add the following format to my catalog so that my `.sas7bdat` file is readable with SAS, but this unfortunately fails with `haven`:

```sas
libname catout 'your/path';
Proc format lib=catout;
Value $ate ;
run;
```

This SAS code creates a `formats.sasb7cat` catalog file ([link](https://github.com/tidyverse/haven/files/10338099/formats.zip)) that weighs only 17ko.

Using `read_sas(input, catalog)` with this catalog file will output the following error, regardless of the input `.sas7bdat` file:
> `Failed to parse xxx.sas7bdat: Unable to allocate memory.`

I'm not sure whether this relates to ReadStats so I posted it here, sorry if this was not the thing to do.

### LINKED ISSUE #707: CRAN check failure
https://cran.r-project.org/web/checks/check_results_haven.html

```
Version: 2.5.1 
Check: compiled code 
Result: WARN 
    File ‘haven/libs/haven.so’:
     Found ‘__sprintf_chk’, possibly from ‘sprintf’ (C)
     Objects: ‘readstat/spss/readstat_por.o’,
     ‘readstat/stata/readstat_dta_write.o’
    
    Compiled code should not call entry points which might terminate R nor
    write to stdout/stderr instead of to the console, nor use Fortran I/O
    nor system RNGs nor [v]sprintf.
    
    See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual. 
Flavors: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/haven-00check.html), [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/haven-00check.html), [r-devel-linux-x86_64-fedora-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/haven-00check.html)

Version: 2.5.1 
Check: whether package can be installed 
Result: WARN 
    Found the following significant warnings:
     readstat/readstat_bits.h:10:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/readstat_bits.c:11:5: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/readstat_variable.c:5:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/readstat_variable.c:8:25: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/sas/../readstat_bits.h:10:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/sas/ieee.c:19:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/sas/ieee.c:99:5: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/sas/readstat_sas.c:123:15: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/sas/readstat_xport_read.c:48:21: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/spss/readstat_por.h:34:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/spss/readstat_por.c:67:12: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/spss/readstat_por_write.c:170:25: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/spss/../readstat_bits.h:10:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     readstat/stata/../readstat_bits.h:10:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    See ‘/home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/haven.Rcheck/00install.out’ for details.
    * used C compiler: ‘gcc-12 (Debian 12.2.0-13) 12.2.0’
    * used C++ compiler: ‘g++-12 (Debian 12.2.0-13) 12.2.0’ 
Flavor: [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/haven-00check.html)
```

@lionel- can you remind me what we need to do for the "warning: function declaration isn’t a prototype" problem?

### PR DESCRIPTION
**Pull request by gorcha**
This update includes a heap of bug fixes:
* Fix various SAS catalog file reading bugs (fix #529, fix #653, fix #680, fix #696, fix #705).
* Increase maximum SAS page file size to 16MB (fix #697).
* Ignore invalid SAV timestamp strings (fix #683).
* Fix compiler warnings (fix #707).

Includes the ReadStat hacks:
* Windows iconv hack - c1f9f1997ad35e237629c5aba932a950caa79e1a
* Solaris hack - 4a878a10a290a164c24f30edfb7e5192b1f15b1d

### CODE REVIEW

**Comment by hadley** [comment]
I need to get a release to CRAN by the 26th; do you think we can make that work?

**Comment by gorcha** [comment]
Yeah that should work - the ReadStat update fixes the compiler warnings in R-devel. There are a couple of other little things I'd like to do before the next release that I can sort out tomorrow.

**Comment by hadley** [comment]
@gorcha thanks, it's much appreciated 😄

**Comment by gorcha** [comment]
No worries at all! :slightly_smiling_face:

**Pull request merged**
