### PR TITLE
Add skip rows to readers

### LINKED ISSUE #370: Read subset of rows
The motivation for this is similar to #248 

People send me large SAS files (say, 5M rows x 1k columns) that are too large to read into R on my computer. I end up having to get the sender to chop the file into smaller sets of rows because I don't have access to SAS to do this myself.

If I could specify an arbitrary contiguous set of rows to read I could split the file myself without having to go back to the sender.

Thanks

### PR DESCRIPTION
**Pull request by mikmart**
Updated ReadStat to [v1.1.0](https://github.com/WizardMac/ReadStat/releases/tag/v1.1.0), which has `readstat_set_row_offset()` allowing the parser to skip rows; and added a `skip` argument to the R functions to set the offset.

Closes #370.

### CODE REVIEW

**Comment by mikmart** [comment]
Some timings:

``` r
library(haven)

sas <- tempfile(fileext = ".sas7bdat")
sav <- tempfile(fileext = ".sav")
dta <- tempfile(fileext = ".dta")
xpt <- tempfile(fileext = ".xpt")
por <- tempfile(fileext = ".por")
csv <- tempfile(fileext = ".csv")

write_sas(manycars <- purrr::map_df(seq_len(1e5), ~ mtcars), sas)
write_sav(manycars <- purrr::map_df(seq_len(1e5), ~ mtcars), sav)
write_dta(manycars <- purrr::map_df(seq_len(1e5), ~ mtcars), dta)
write_xpt(manycars <- purrr::map_df(seq_len(1e5), ~ mtcars), xpt)
readr::write_csv(manycars <- purrr::map_df(seq_len(1e5), ~ mtcars), csv)

n <- nrow(manycars)
m <- 10000

read_csv <- purrr::quietly(readr::read_csv)

bench::mark(
  read_sas(sas, n_max = m),
  read_sas(sas, skip = n - m),
  read_sav(sav, n_max = m),
  read_sav(sav, skip = n - m),
  read_dta(dta, n_max = m),
  read_dta(dta, skip = n - m),
  read_xpt(xpt, n_max = m),
  read_xpt(xpt, skip = n - m),
  read_csv(csv, n_max = m),
  read_csv(csv, skip = n - m),
  check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 10 x 6
#>    expression                       min   median `itr/sec` mem_alloc
#>    <bch:expr>                  <bch:tm> <bch:tm>     <dbl> <bch:byt>
#>  1 read_sas(sas, n_max = m)    415.58ms 463.73ms     2.16     1.25MB
#>  2 read_sas(sas, skip = n - m) 733.94ms 733.94ms     1.36   862.38KB
#>  3 read_sav(sav, n_max = m)     15.06ms  23.56ms    40.6    896.99KB
#>  4 read_sav(sav, skip = n - m)  16.21ms  20.66ms    46.4    862.38KB
#>  5 read_dta(dta, n_max = m)     19.83ms     28ms    34.8     895.3KB
#>  6 read_dta(dta, skip = n - m)  21.96ms  28.15ms    32.1    862.38KB
#>  7 read_xpt(xpt, n_max = m)     41.03ms  63.98ms    14.7      9.26MB
#>  8 read_xpt(xpt, skip = n - m)    6.93s    6.93s     0.144    9.23MB
#>  9 read_csv(csv, n_max = m)     14.69ms  17.33ms    53.5      1.96MB
#> 10 read_csv(csv, skip = n - m) 592.45ms 592.45ms     1.69     1.14MB
#> # ... with 1 more variable: `gc/sec` <dbl>
```

<sup>Created on 2019-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
This is wonderful — thanks so much for your hard work on all these features!

**Comment by mikmart** [comment]
Thanks! Happy to have a chance to contribute. And I'm learning a lot in the process!

**Comment by hadley** [comment]
@mikmart I'm not always watching haven, so please feel free to ping me with `@hadley` if you need me to look at something. Are there other features that you're interested in working on?

**Comment by mikmart** [comment]
@hadley that's good to know! I'll be a little more liberal with the mentions in the future, then.

I hadn't had anything on my mind -- but now that you mention it, I think I would be interested in having a look at #477. If I understand correctly, that would mean turning `haven_labelled` into a vctrs vector?

**Comment by hadley** [comment]
@mikmart oh yeah, that would be great — https://vctrs.r-lib.org/articles/s3-vector.html should be enough to get you started, but please let me know if you get stuck so I can improve the docs.

**Pull request merged**
