### PR TITLE
Tidyverse upkeep

### PR DESCRIPTION
**Pull request by gorcha**
This PR makes a bunch of tidyverse upkeep changes, closing #672 and #661.

The [condition formatting](https://rlang.r-lib.org/reference/topic-condition-formatting.html) write-up in rlang recommends using `cli::cli_abort()` instead of `rlang::abort()`, but it's relatively new so I'm a bit unsure about replacing all the error messaging with it yet (it would move cli from suggests to imports and need >=3.0.0) - what do you think?

### CODE REVIEW

**Comment by hadley** [comment]
It's fine to move directly to `cli_abort()` if you want to. It makes it much easier to construct error messages since you can use glue.

**Comment by gorcha** [comment]
OK cool, have done! I think we're ready for release once this is merged.

**Review by hadley — APPROVED** [review]
Looks great, thanks for working on this!

Do you want to start the release process too? (i.e. call `use_release_issue()` and then start on the bullets?)

**Comment by gorcha** [comment]
No worries at all :slightly_smiling_face:

And yep, shall do!

**Pull request merged**
